# Generated by Django 4.2.20 on 2025-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0002_alter_sushi_ingredients_alter_sushi_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sushi',
            new_name='Order',
        ),
    ]
