# Generated by Django 4.2.20 on 2025-05-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0003_rename_sushi_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.CharField(choices=[('Green Tea', 'Green Tea'), ('Matcha Latte', 'Matcha Latte'), ('Ramune Soda', 'Ramune Soda'), ('Yuzu Juice', 'Yuzu Juice'), ('Calpico', 'Calpico'), ('Iced Genmaicha', 'Iced Genmaicha'), ('Sparkling Water', 'Sparkling Water'), ('Cold Brewed Hojicha', 'Cold Brewed Hojicha'), ('Plum Juice', 'Plum Juice')], max_length=100)),
                ('starter', models.CharField(choices=[('Edamame', 'Edamame'), ('Miso Soup', 'Miso Soup'), ('Seaweed Salad', 'Seaweed Salad'), ('Gyoza', 'Gyoza'), ('Takoyaki', 'Takoyaki'), ('Agedashi Tofu', 'Agedashi Tofu'), ('Sunomono', 'Sunomono'), ('Shishito Peppers', 'Shishito Peppers'), ('Chawanmushi', 'Chawanmushi')], max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.order')),
            ],
        ),
    ]
