# Generated by Django 4.2.20 on 2025-05-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0004_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='side',
            old_name='cat',
            new_name='order',
        ),
    ]
