# Generated by Django 4.2.20 on 2025-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0006_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tuna', 'Tuna'), ('Salmon', 'Salmon'), ('Crab Stick', 'Crab Stick'), ('Shrimp Tempura', 'Shrimp Tempura'), ('Eel', 'Eel'), ('Avocado', 'Avocado'), ('Cucumber', 'Cucumber'), ('Cream Cheese', 'Cream Cheese'), ('Spicy Mayo', 'Spicy Mayo'), ('Wasabi', 'Wasabi'), ('Pickled Ginger', 'Pickled Ginger'), ('Tamago (Sweet Egg)', 'Tamago (Sweet Egg)'), ('Tobiko (Fish Roe)', 'Tobiko (Fish Roe)'), ('Sesame Seeds', 'Sesame Seeds'), ('Chili Flakes', 'Chili Flakes'), ('Spring Onion', 'Spring Onion'), ('Carrot', 'Carrot'), ('Lettuce', 'Lettuce'), ('Radish', 'Radish'), ('Seaweed Salad', 'Seaweed Salad'), ('Teriyaki Sauce', 'Teriyaki Sauce'), ('Soy Sauce', 'Soy Sauce'), ('Rice Vinegar', 'Rice Vinegar'), ('Sriracha', 'Sriracha')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Maki', 'Maki'), ('Nigiri', 'Nigiri'), ('Uramaki', 'Uramaki'), ('Temaki', 'Temaki'), ('Sashimi', 'Sashimi'), ('Chirashi', 'Chirashi'), ('Inari', 'Inari')], max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(to='sushi_app.ingredient'),
        ),
    ]
