# Generated by Django 4.2.20 on 2025-05-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0008_remove_order_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='side',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.order'),
        ),
    ]
