# Generated by Django 4.2.20 on 2025-05-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0009_remove_order_user_alter_side_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.order'),
        ),
    ]
