# Generated by Django 4.2.20 on 2025-05-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0011_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sushi_app.order'),
        ),
    ]
