# Generated by Django 4.2.20 on 2025-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0012_alter_side_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Maki', 'Maki'), ('Nigiri', 'Nigiri'), ('Uramaki', 'Uramaki'), ('Temaki', 'Temaki')], max_length=100),
        ),
    ]
